/*STRING FUNCTIONS PART 2*/

SELECT LTRIM('    STUTI SHAHU')

SELECT PATINDEX('%T%', 'STUTI')/*RETURNS THE FIRST MATCHED INDEX*/

SELECT STUFF('STUTI', 1, 3, 'ABC') /*DELETES A SEPCIFIC NUMBER OF CHARACTERS FROM A POSITION AND INSERTS SOME OTHER CHARACTERS IN THEIR POSITION*/

SELECT RTRIM ('STUTI SHAHU     ')

SELECT TRANSLATE('Monday', 'Monday', 'Sunday')

