/*MAX RECURSION*/

WITH CTE(EMPLOYEEID, MANAGERID, TITLE) AS
(
SELECT EmployeeID,ManagerID, TITLE FROM dbo.MyEmployees WHERE MANAGERID IS NOT NULL
UNION ALL
SELECT CTE.EMPLOYEEID, CTE.MANAGERID, CTE.TITLE
FROM CTE
JOIN dbo.MYEmployees AS E
ON CTE.MANAGERID=E.EMPLOYEEID
)
SELECT EMPLOYEEID, MANAGERID, TITLE
FROM CTE
OPTION(MAXRECURSION 2)

/*SOLVED MAXRECURSION*/

WITH CTE(EMPLOYEEID, MANAGERID, Title)
AS
(
SELECT EMPLOYEEID, MANAGERID, Title FROM MYEMPLOYEES WHERE MANAGERID IS NOT NULL
UNION ALL
SELECT E.EMPLOYEEID, E.MANAGERID, E.TITLE
FROM MYEMPLOYEES AS E
JOIN CTE ON E.MANAGERID=CTE.EMPLOYEEID)
SELECT EMPLOYEEID, MANAGERID, TITLE FROM CTE