/*PROGRAMMING CONSTRUCT*/

/*IF ELSE CLAUSE*/
IF DATENAME(WEEKDAY, GETDATE()) IN (N'Saturday', N'Sunday')
SELECT 'WEEKEND';
ELSE
SELECT 'WEEKDAY'

/*WHILE LOOP*/
WHILE(SELECT AVG(ListPrice) FROM Production.Product)>$300
BEGIN
UPDATE Production.Product
SET ListPrice= ListPrice*2
SELECT MAX(LISTPRICE) FROM Production.Product
IF (SELECT MAX(LISTPRICE) FROM Production.Product)>450
BREAK
ELSE
CONTINUE
END
PRINT 'TOO MUCH FOR THE MARKET TO BEAR'

/*SIMPLE WHILE LOOP*/

WHILE(SELECT AVG(LISTPRICE) FROM Production.Product)<$300
BEGIN
UPDATE Production.Product
SET ListPrice=ListPrice*2
SELECT MAX(LISTPRICE) FROM Production.Product
IF(SELECT MAX(LISTPRICE) FROM PRODUCTION.PRODUCT)>$500
BREAK
END