WITH SALES_CTE(SALESPERSONID, TOTALSALES, SALESYEAR)
AS
(
SELECT SALESPERSONID, SUM(TOTALDUE) AS TOTALSALES, YEAR(ORDERDATE) AS SALESYEAR
FROM SALES.SALESORDERHEADER
WHERE SALESPERSONID IS NOT NULL
GROUP BY SALESPERSONID, YEAR(ORDERDATE)
)
,
SALES_QUOTE_CTE(BUSINESSENTITYID, SALESQUOTA, SALESQUOTAYEAR)
AS
(
SELECT BUSINESSENTITYID, SUM(SALESQUOTA) AS SALESQUOTA, YEAR(QUOTADATE) AS SALESQUOTADATE
FROM SALES.SalesPersonQuotaHistory
GROUP BY BUSINESSENTITYID, YEAR(QUOTADATE)
)
SELECT SALESPERSONID, SALESYEAR, FORMAT(TOTALSALES, 'C', 'en-us') AS AMT_ABV_OR_BELOW_QUOTA
FROM SALES_CTE
JOIN SALES_QUOTE_CTE ON SALES_QUOTE_CTE.BUSINESSENTITYID=SALES_CTE.SALESPERSONID
AND SALES_CTE.SALESYEAR=SALES_QUOTE_CTE.SALESQUOTAYEAR
ORDER BY SALESPERSONID, SALESYEAR