SET NOCOUNT ON
DECLARE @ID int, @name varchar(50), @salary int
DECLARE cur_emp CURSOR
STATIC FOR
SELECT EMPLOYEE_ID, FIRST_NAME, Salary from employees
OPEN cur_emp
FETCH NEXT FROM cur_emp 
IF @@CURSOR_ROWS>0
BEGIN 
WHILE @@FETCH_STATUS=0
BEGIN
IF @salary BETWEEN 30000 AND 40000
UPDATE employees SET SALARY= SALARY+5000

ELSE IF @salary BETWEEN 40000 AND 55000
UPDATE employees SET SALARY= SALARY+7000

ELSE
UPDATE employees SET SALARY= SALARY+9000

FETCH NEXT FROM cur_emp 
END
END
CLOSE cur_emp
DEALLOCATE cur_emp
SET NOCOUNT OFF
