/*STRING FUNCTIONS*/

SELECT Name= Title+ ''+ left(FirstName, 1)+ '.'+ LastName FROM Person.Person

SELECT ASCII('S') /*OPPOSITE IS THE CHAR FUNCTION, RETURNS THE CHARACTER BASED ON ASCII CODE*/

SELECT ASCII('s')

SELECT CHARINDEX('T', FirstName) AS POSITIONMATCHED FROM Person.Person

SELECT CONCAT('STUTI', 'SHAHU') /*TWO OR MORE STRINGS ARE CONCATED*/

SELECT DIFFERENCE('ICY', 'I SEE')/*ALMOST SIMILAR SOUNDEX VALUES*/

DECLARE @d DATETIME= '06/20/2022';
SELECT FORMAT (@d, 'd', 'no')

SELECT LOWER('STUTI SHAHU')

SELECT UPPER('stuti shahu')
