/*CREATING A TRIAL DATABASE FOR THE MINI PORJECT*/

CREATE DATABASE HOTSTAR_TRIAL
USE HOTSTAR_TRIAL

CREATE TABLE Customer
(
CustomerID INT PRIMARY KEY,
FirstName VARCHAR(100),
LastName VARCHAR(100),
Email VARCHAR(100),
PHONE VARCHAR(10),
Password VARCHAR(100),
)

CREATE TABLE Subscription
(
SubscriptionID int PRIMARY KEY,
CustomerID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMERID),
SUBSCRIPTION_TYPE_ID INT FOREIGN KEY REFERENCES SUBSCRIPTIONTYPE(TYPEID),
SUBSCRIPTIONDATE DATE,
EXPIRATIONDATE DATE,
PAYMENTMETHOD VARCHAR(200)
)

CREATE TABLE SubscriptionType
(
TypeID INT PRIMARY KEY,
TypeName VARCHAR(100),
Amount INT,
DURATION VARCHAR(20),
NumberOFScreens INT
)

CREATE TABLE SHOW
(
ShowID INT PRIMARY KEY,
ShowName VARCHAR(200),
Genre VARCHAR(100),
Language VARCHAR(200),
Paid BIT,
ReleaseDate DATE
)