/*ASSIGNMENT Q1*/

CREATE PROCEDURE PRC_CityCustomers @name varchar(100)
AS 
BEGIN
SET NOCOUNT ON;
SELECT CName

    FROM Deposit 

    WHERE NOT CName = @name AND BName IN (SELECT B.BName FROM Branch B JOIN Deposit D ON B.BName = D.BName 

        WHERE B.City = (SELECT B.City FROM Branch B JOIN Deposit D ON B.BName = D.BName WHERE D.CName = @name));  

END

 /*ASSIGNMENT Q2*/

 /* ASSIGNMENT Q3*/

 CREATE PROCEDURE PRC_CountCity  @CITYNAME VARCHAR(100)
 AS
 BEGIN
 SET NOCOUNT ON
 SELECT COUNT(CNAME) FROM CUSTOMER WHERE CITY=@CITYNAME
 END
 SET NOCOUNT OFF

 EXECUTE PRC_CountCity 'DELHI'

 /* ASSIGNMENT Q4*/

 CREATE PROCEDURE PRC_CityInJson @cityname1 varchar(100)
 AS
 BEGIN 
 SET NOCOUNT ON
 SELECT COUNT(CUSTOMER.CNAME) AS CNAME FROM CUSTOMER JOIN BORROW ON CUSTOMER.CNAME= BORROW.CNAME WHERE CITY=@cityname1 AND BORROW.BNAME= 'MUMBAI' OR BORROW.BNAME='DELHI' FOR JSON AUTO
 END
 SET NOCOUNT OFF

 EXECUTE PRC_CityInJson 'DELHI'

 /*ASSIGNMENT Q5*/

 CREATE PROCEDURE CustomerInBranchName @bname varchar(80)
 AS
 BEGIN
 SET NOCOUNT ON
 SELECT COUNT(CNAME) FROM CUSTOMER WHERE CITY=(SELECT CITY FROM BRANCH WHERE BNAME=@bname)
 END
 SET NOCOUNT OFF

 EXECUTE CustomerInBranchName 'ANDHERI'

 /*ASSIGNMENT Q6*/

 INSERT INTO DEPOSIT VALUES (124, 'SUNIL', 'KAROLBAGH', 10000, '2022-04-19')
 INSERT INTO DEPOSIT VALUES(125, 'KRANTI', 'ANDHERI', 9000, '2022-3-07')

 CREATE PROCEDURE InputDeposit @ipjson nvarchar(max)
 AS 
 BEGIN
 SET NOCOUNT OFF
INSERT INTO DEPOSIT  SELECT * FROM OPENJSON (@IPJSON) WITH (ACTNO VARCHAR(5), CNAME VARCHAR(18), BNAME VARCHAR(18), AMOUNT INT, ADATE DATE) WHERE AMOUNT>10 AND ADATE=CONVERT(DATE, GETDATE())
END
SET NOCOUNT ON

EXECUTE InputDeposit '{"ACTNO": "E3", "CNAME": "MADHURI", "BNAME": "DHARAMPETH", "AMOUNT": 0, "ADATE": "2021-12-27"}'
