CREATE TABLE EMPLOYEE(
Emplpoyee_ID int PRIMARY KEY IDENTITY(1,1),
First_Name varchar(50),
Last_Name varchar(50),
Salary int,
Joining_Date DATE,
Department varchar(50),
Manager_ID int
)

INSERT INTO EMPLOYEE VALUES('John', 'Abraham', 1000000, '2013/1/1', 'Banking', NULL)

INSERT INTO EMPLOYEE VALUES('Michael', 'Clarke', 800000, '2013/1/1', 'Insurance', 1)

INSERT INTO EMPLOYEE VALUES('Roy', 'Thomas', 700000, '2013/2/1', 'Banking', 1)

INSERT INTO EMPLOYEE VALUES('Tom', 'Jose', 600000, '2013/2/1', 'Insurance', 2)

INSERT INTO EMPLOYEE VALUES('Tom', 'Jose', 600000, '2013/2/1', 'Insurance', 2)


CREATE TABLE INCENTIVE(
Employee_Ref_ID  int FOREIGN KEY REFERENCES EMPLOYEE(Emplpoyee_ID),
INCENTIVE_DATE DATE,
INCENTIVE_AMOUNT int

)

INSERT INTO INCENTIVE VALUES(2, '2013/02/01', 5000)


INSERT INTO INCENTIVE VALUES(3, '2013/02/01', 3000)


INSERT INTO INCENTIVE VALUES(4, '2013/02/01', 4000)


SELECT INCENTIVE.INCENTIVE_DATE, Employee_Ref_ID FROM INCENTIVE LEFT JOIN EMPLOYEE ON EMPLOYEE.Emplpoyee_ID=INCENTIVE.Employee_Ref_ID


SELECT EMPLOYEE.FIRST_NAME, INCENTIVE.INCENTIVE_AMOUNT FROM EMPLOYEE LEFT JOIN INCENTIVE ON EMPLOYEE.Emplpoyee_ID=INCENTIVE.Employee_Ref_ID AND INCENTIVE.INCENTIVE_AMOUNT>=3000 

SELECT First_Name,INCENTIVE_AMOUNT FROM EMPLOYEE
LEFT JOIN INCENTIVE
ON EMPLOYEE.Employee_ID = INCENTIVE.Employee_Ref_ID

SELECT First_Name,Last_Name, MANAGERNAME FROM EMPLOYEE

SELECT Employee_ID ,COALESCE (Incentive_Amount,0) 
FROM Employee LEFT JOIN Incentive 
ON Employee.Employee_ID = Incentive.Employee_Ref_ID




