/*CREATING AND CALLING SCALAR FUNCTION*/

CREATE FUNCTION MONTHLYSAL(@PAYRATE FLOAT)
RETURNS FLOAT
AS
BEGIN
RETURN(@PAYRATE *8*30)
END

/*CALLING A SCALAR FUNCTION*/
DECLARE @PAY FLOAT
SET @PAY= DBO.MONTHLYSAL(10.25)
PRINT @PAY

/*ANOTHER SCALAR FUNCTION*/
CREATE FUNCTION DBO.GETSTOCK(@PRODUCTID INT)
RETURNS INT
AS 
BEGIN
DECLARE @RET INT
SELECT @RET= SUM(P.QUANTITY)
FROM Production.ProductInventory P
WHERE P.ProductID= @PRODUCTID
AND P.LocationID='6'
IF(@RET IS NULL)
SET @RET=0
RETURN @RET
END

SELECT PRODUCTMODELID, NAME, DBO.GETSTOCK(PRODUCTID) FROM Production.Product WHERE ProductModelID BETWEEN 75 AND 80

