ALTER TRIGGER HUMANRESOURCES.trgSHIFTDelete
ON
HUMANRESOURCES.SHIFT
FOR DELETE
AS
PRINT 'DELETION OF SHIFT IS NOT ALLOWED'
ROLLBACK TRANSACTION
RETURN

DELETE FROM HumanResources.Shift WHERE ShiftID=6