/*SWITCH CASE*/
SELECT * FROM PRODUCTION.PRODUCT
SELECT PRODUCTNUMBER, CATEGORY=
CASE PRODUCTLINE
WHEN 'R' THEN 'ROAD'
WHEN 'M' THEN 'MOUNTAIN'
WHEN 'T' THEN 'TOURING'
WHEN 'S' THEN 'OTHER SALE ITEMS'
ELSE 'NOT FOR SALE'
END,
NAME
FROM PRODUCTION.PRODUCT
ORDER BY PRODUCTNUMBER

