/* CTE PRACTICE*/
/*CREATING A SIMPLE TABLE EXPRESSION*/

WITH SALES_CTE(SalesPersonID, SalesOrderID, SalesYear)
AS
(
SELECT SALESPERSONID, SALESORDERID, YEAR(ORDERDATE) AS SALESYEAR
FROM SALES.SalesOrderHeader
WHERE SalesPersonID IS NOT NULL
)

SELECT SALESPERSONID, COUNT(SALESORDERID) AS TOTALSALES, SALESYEAR
FROM SALES_CTE
GROUP BY SalesYear, SalesPersonID
ORDER BY SALESPERSONID, SALESYEAR
