CREATE VIEW ViewOne AS
SELECT CONCAT(EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME) AS NAME, JOBS.JOB_TITLE, employees.DEPARTMENT_ID, departments.DEPARTMENT_NAME FROM employees JOIN JOBS ON employees.JOB_ID=JOBS.JOB_ID JOIN departments ON employees.DEPARTMENT_ID=departments.DEPARTMENT_ID AND departments.LOCATION_ID=2400

SELECT * FROM ViewOne


CREATE VIEW ViewTwo
AS
SELECT DEPARTMENT_NAME, COUNT(*) AS 'No of Employees'
FROM departments INNER JOIN employees
ON employees.DEPARTMENT_ID = departments.DEPARTMENT_ID
GROUP BY departments.DEPARTMENT_ID ,departments.DEPARTMENT_NAME

SELECT * FROM ViewTwo



CREATE VIEW ViewThree 
AS
SELECT employees.EMPLOYEE_ID, JOBS.JOB_TITLE, DATEDIFF(DAY, JOB_HISTORY.START_DATE, JOB_HISTORY.END_DATE) AS DATE_DIFF FROM employees JOIN job_history ON EMPLOYEES.DEPARTMENT_ID=job_history.DEPARTMENT_ID JOIN jobs ON job_history.JOB_ID=JOBS.JOB_ID 

SELECT * FROM ViewThree

