/*INLINE TABLE-VALUED FUNCTION*/

CREATE FUNCTION DBO.SALESBYSTORE(@STOREID INT)
RETURNS TABLE
AS
RETURN 
(
SELECT P.PRODUCTID, P.NAME,SUM(SD.LINETOTAL) AS 'TOTAL'
FROM Production.Product AS P JOIN SALES.SalesOrderDetail AS SD ON SD.ProductID=P.ProductID
JOIN Sales.SalesOrderHeader AS SH ON SH.SalesOrderID=SD.SalesOrderID
JOIN Sales.Customer AS C ON SH.CUSTOMERID=C.CustomerID
WHERE C.STOREID= @STOREID
GROUP BY P.ProductID, P.NAME);
/*CALLING THE FUNCTION*/
SELECT * FROM DBO.SALESBYSTORE(602)