/* IMPLEMENTING ISOLATION LEVELS*/

SET TRANSACTION ISOLATION LEVEL
READ COMMITTED
BEGIN TRANSACTION TR
BEGIN TRY
UPDATE Person.EmailAddress
SET EmailAddress= 'JOLYN@YAHOO.COM'
WHERE BusinessEntityID=101
UPDATE Person.BusinessEntityAddress
SET AddressID=328
WHERE BusinessEntityID=1
COMMIT TRANSACTION TR1
SELECT 'TRANSACTION EXECUTED'
END TRY
BEGIN CATCH
ROLLBACK TRANSACTION TR1
SELECT 'TRANSACTION ROLLBACK'
END CATCH