use NEWDB

CREATE NONCLUSTERED INDEX[NCI_PHNO] ON dbo.employees
(
[PHONE_NUMBER] ASC
)

SELECT * FROM employees ORDER BY EMPLOYEE_ID/*USING NO INDEXING- COST 100% ON THE CLUSTERED INDEX*/

SELECT * FROM employees WHERE EMPLOYEE_ID=100

SELECT * FROM employees WHERE EMPLOYEE_ID=100 AND PHONE_NUMBER='515.123.4567'

SELECT *
FROM employees WITH(INDEX(NCI_PHNO))/*FORCE USE THE INDEX, COST DROPS BY AROUND 13%*/