CREATE TRIGGER HUMANRESOURCES.trgInsertShift
ON HUMANRESOURCES.SHIFT
FOR INSERT
AS
DECLARE @MODIFIEDDATE DATETIME
SELECT @MODIFIEDDATE=MODIFIEDDATE FROM INSERTED
IF(@MODIFIEDDATE!=CONVERT(DATE, GETDATE()))
BEGIN 
PRINT 'THE MODUFIED DATE SHOULD BE THE CURRENT DATE. AND WE CANNOT INSERT IT'
ROLLBACK TRANSACTION
END

INSERT INTO HumanResources.Shift VALUES ( 'STUTI', '02:32', '05:32', '2022-07-04')
INSERT INTO HumanResources.Shift VALUES ( 'HRITIKA', '15:09', '19:04', '2022-07-04')