/*PRACTICING TRANSACTION*/

BEGIN TRY
BEGIN TRANSACTION TR2
DELETE FROM CUSTOMER WHERE CNAME='STUTI'--WONT THROW UNLESS THE STATEMENT ITSEL DOES SO OR THERE IS AN ERROR THROW OR RAISEERROR STATEMENT WRITTEN. ROLLBACK ONLY HAPPENS WHEN THE CONTROL MOVES ONTO THE CATCH BLOCK--
COMMIT TRANSACTION
END TRY
BEGIN CATCH
ROLLBACK TRANSACTION TR2
PRINT 'ROLLBACK!'
END CATCH