/* ISJSON*/
DECLARE @JSON VARCHAR(MAX)
SET @JSON= N'[  
  {"id": 2, "info": {"name": "John", "surname": "Smith"}, "age": 25},
  {"id": 5, "info": {"name": "Jane", "surname": "Smith", "skills": ["SQL", "C#", "Azure"]}, "dob": "2005-11-04T12:00:00"}  
]'; 
SELECT ISJSON(@JSON)/*GIVES 1 WHEN THE PASSED OBJECT IS IN THE JSON FORMAT*/

DECLARE @NOTJSON VARCHAR(MAX)
SET @NOTJSON=0

SELECT ISJSON(@NOTJSON) /*GIVES 0 WHEN PASSED OBJECTS THAT ARENT IN JSON FORMAT, DOESNT TAKE ANY OTHER DATATYPE ONLY VARCHAR(MAX)*/

DECLARE @NULLJSON VARCHAR(MAX)
SET @NULLJSON= NULL
SELECT ISJSON(@NULLJSON)/* GIVES NULL WHEN THE OBJECT IS NULL*/


