/*VIEWS*/

CREATE VIEW HUMANRESOURCES.HIREDATE
AS
SELECT P.FIRSTNAME, P.LASTNAME, E.HIREDATE
FROM HumanResources.Employee AS E JOIN Person.Person AS P
ON E.BusinessEntityID=P.BusinessEntityID

SELECT FIRSTNAME, LASTNAME, HIREDATE FROM HUMANRESOURCES.HIREDATE

--ALTER VIEW
ALTER VIEW HUMANRESOURCES.HIREDATE
AS
SELECT P.FIRSTNAME, P.LASTNAME, E.HIREDATE 
FROM HumanResources.Employee AS E JOIN Person.Person AS P
ON E.BusinessEntityID=P.BusinessEntityID
WHERE HireDate<CONVERT(DATETIME, '20020101', 101)

-- VARIABLES
DECLARE @VARIABLE_DEMO INT
SET @VARIABLE_DEMO=5
PRINT @VARIABLE_DEMO

/*STORED PROCEDURE*/
CREATE PROCEDURE PRC_PRO1
@MEALID INT 
AS
SET NOCOUNT ON
SELECT MEALNAME FROM MEAL WHERE MEALID=@MEALID
GO

EXECUTE DBO.PRC_PRO1 1

/*FUNCTIONS*/

--SCALAR FUNCTION
CREATE FUNCTION MEALNAME (@MEALID INT)
RETURNS  VARCHAR(100)
AS
BEGIN
DECLARE @MEALNAME VARCHAR(100)
SET @MEALNAME= (SELECT MEALNAME FROM MEAL WHERE MEALID=@MEALID)
RETURN @MEALNAME
END
SELECT DBO.MEALNAME(1)



