/*CONVERTING SQL TABLES TO JSON OBJECT*/

SELECT FIRST_NAME, LAST_NAME FROM employees FOR JSON AUTO/* THE FORMAT OF JSON OUTPUT IS AUTOMATICALLY DETERMINED BY THE ORDER OF THE SELECT QUERY, ALTERNATIVE IS PATH FUNCTION*/

SELECT TOP 5 BusinessEntityID AS ID, FirstName AS 'INFO.FIRSTNAME', LastName AS 'INFO.LASTNAME' FROM PersoN.Person FOR JSON PATH /* THIS WAY WE CAN SPECIFY HOW WE NEED THE FORMAT OF THE JSON OBJECT*/




