/*ADVANCED FUNCTIONS*/

SELECT COALESCE (Title, NULL) FROM PERSON.PERSON

SELECT SYSTEM_USER

SELECT CONVERT(int, 25.65) /*CONVERTS THE SECOND ARGUEMENT INTO THE DATA TYPE SPECIFIED IN THE FIRST ARGUEMENT*/

SELECT NULLIF('STUTI', 'SHAHU') /*RETURNS NULL IF BOTH THE EXPRESSIONS ARE EQUAL OR ELSE RETURNS THE FIRST ARGUEMENT*/

SELECT ISNUMERIC(19)/* RETURNS 0 IF THE VALUE ISNT NUMERIC AND 1 IF THE VALUE IS NUMERIC */



